language: python
python:
  - "2.7"
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.15.zip -nv
  - unzip -q google_appengine_1.9.15.zip
  - npm install -g jquery
  - npm install selenium-webdriver
  - npm install -g jasmine-node
  - npm install -g jasmine-jquery

  - cd test
  - chmod +x ./master_test_script.sh
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install NoseGAE"
  - "pip install webtest"
# command to run tests, e.g. python setup.py test
script: ./master_test_script.sh
addons:
  firefox: "17.0"
notifications:
  email: false
#    on_success: change # default: change
#    on_failure: always # default: always
  irc:
    channels:
      - "tim32.org/#cloudappdev"
    template:
      - "Build #%{build_number} (%{branch} / %{commit} : %{author}): %{commit_message}"
      - "Details: %{message} @ %{build_url}"
