language: python
python:
  - "2.7"
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.13.zip -nv
  - unzip -q google_appengine_1.9.13.zip
  - npm install selenium-webdriver
  - npm install -g jasmine-node
  - chmod +x ./test/master_test_script.sh
  - cd test
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install NoseGAE"
  - "pip install webtest"
#  - "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
script: ./test/master_test_script.sh
notifications:
  email: false
  irc:
    channels:
      - "tim32.org/#cloudappdev"
    template:
      - "Build #%{build_number} (%{branch} / %{commit} : %{author}): %{commit_message}"
      - "Details: %{message} @ %{build_url}"