language: python
python:
  - "2.7"
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.14.zip -nv
  - unzip -q google_appengine_1.9.14.zip
  - npm install selenium-webdriver
  - npm install -g jasmine-node
  - cd test
  - chmod +x ./master_test_script.sh
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install NoseGAE"
  - "pip install webtest"
#  - "pip install -r requirements.txt"
# command to run tests, e.g. python setup.py test
script: ./master_test_script.sh
addons:
  firefox: "17.0"
notifications:
  email: false
  irc:
    channels:
      - "tim32.org/#cloudappdev"
    template:
      - "Build #%{build_number} (%{branch} / %{commit} : %{author}): %{commit_message}"
      - "Details: %{message} @ %{build_url}"
