application: jinglr-music
version: 1
runtime: python27
api_version: 1
threadsafe: yes
inbound_services:
- warmup
- channel_presence
handlers:
- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: favicon\.ico
  
- url: /public
  static_dir: public

- url: /admin/initialdata
  script: admin.application
  login: admin
  
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /api/songs/search.*
  script: songs_search.application

- url: /_ah.*
  script: admin.application

- url: /tasks/.*
  script: taskqueue_handlers.application
  login: admin

- url: /.*/users/self.*
  script: users.application
  login: required

- url: /web/users.*
  script: users.application
  login: required

- url: /api/users.*
  script: users.application

- url: /web/songs.*
  script: songs.application
  login: required

- url: /api/songs.*
  script: songs.application

- url: /dashboard
  script: main.application
  login: required

- url: /search.*
  script: main.application
  login: required

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
