application: jinglr-music
version: 1
runtime: python27
api_version: 1
threadsafe: yes
inbound_services:
- warmup
- channel_presence
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /public
  static_dir: public

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /songs/search.*
  script: songs_search.application

- url: /auth.*
  script: auth.application

- url: /_ah.*
  script: admin.application

- url: /songs.*
  script: songs_get.application

- url: /tasks/.*
  script: taskqueue_handlers.application
  login: admin

- url: /users.*
  script: users.application
  
- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
